### ISSUE TITLE
update.

### ISSUE THREAD

**Issue by Grim-reap3r** [Arisamiga/Discord-Giveaway-Bot#2]
Hello.

When you create new giveaway can you add two options.
Name of the GA and discriptions where u can place rules.

Also can you block so people can only use one emoji and stop adding random...

**Comment by Arisamiga** [comment]
Hello @Grim-reap3r!

You are able to add a title for the giveaway using the command `g!giveaway (Time[m for Minutes or h for Hours]) (Channel Id) (Name of giveaway/prize)`. You are not able to add descriptions but you can probably post them on the channel before starting the giveaway as the embed messages have a limit on how many letters they can have.

To stop people from adding random emojis to the giveaway you can disable the setting "Add Reactions" under the permissions on the discord channel.
<img width="464" alt="Screenshot 2022-07-08 at 13 05 05" src="https://user-images.githubusercontent.com/64918822/177988779-6294a4f1-5b2f-4f60-85a7-eaaaa967eda7.png">

If you have further questions let me know!

Have a nice day!
Arisamiga
